apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.jackett.appName }}-pvc-config

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jackett.pvc.storageSize }}
