apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.prowlarr.appName }}-pvc-config

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prowlarr.pvc.storageSize }}
