- name: Instalar la release de Helm config desde charts-apps/config
  kubernetes.core.helm:
    name: config
    chart_ref: "{{ repo_path }}/charts-apps/config"
    release_namespace: "{{ chart_namespace }}"
    kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
    values:
      appSecret:
        data:
          APP_USER: "{{ APP_USER }}"
          APP_PASSWORD: "{{ APP_PASSWORD }}"
