apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecret.name }}
  namespace: {{ .Values.namespace }}

type: {{ .Values.appSecret.type }}

stringData:
{{- toYaml .Values.appSecret.data | nindent 2 }}
