---
- name: Crear directorio .kube para el usuario
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.kube"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0700'

- name: Copiar kubeconfig al entorno del usuario
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ ansible_env.HOME }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0600'
  become: true

- name: Añadir KUBECONFIG al archivo .bashrc del usuario
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export KUBECONFIG=~/.kube/config'
    state: present
    create: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'

- name: Validar acceso a K3s recargando KUBECONFIG en la misma línea
  ansible.builtin.shell: KUBECONFIG=~/.kube/config kubectl get nodes
  register: k3s_status
  changed_when: false