apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mi-chart.name" . }}-deployment

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ include "mi-chart.name" . }}
  
  template:
    metadata:
      labels:
        app: {{ include "mi-chart.name" . }}
    
    spec:      
      containers:
        - name: {{ include "mi-chart.name" . }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: PUID
              value: "1000"
            
            - name: PGID
              value: "1000"
            
            - name: TZ
              value: Europe/Madrid
            
            - name: SQLITE_DATABASE
              value: dbnextcloud

            - name: NEXTCLOUD_ADMIN_USER
              value: {{ .Values.configService.user }}

            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: {{ .Values.configService.password }}

            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: {{ printf "%s %s.%s" .Values.configService.ip (include "mi-chart.name" .) .Values.httpRoute.domain | quote }}
          
          ports:
            - name: {{ .Values.service.portHttpName }}
              containerPort: {{ .Values.service.targetPort }}
          
          volumeMounts:
            - name: config
              mountPath: {{ .Values.storage.mountPathConfig }}

            # - name: customApps
            #   mountPath: {{ .Values.storage.mountPathCustomApps }}
            
            - name: data
              mountPath: /var/www/html/data
      
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "mi-chart.name" . }}-pvc-config

        # - name: customApps
        #   persistentVolumeClaim:
        #     claimName: {{ include "mi-chart.name" . }}-pvc-customApps

        - name: data
          hostPath:
            path: {{ printf "%s/%s" .Values.storage.localStoragePath "nextcloud-data" | quote }}
            type: Directory
